'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class PopupStr
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CustomizerGod.PopupStr", GetType(PopupStr).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Access denied while trying to edit registry.
    '''
    '''Please do the following manually:
    '''
    '''1. Open the Registry Editor by typing regedit.exe in run or search.
    '''
    '''2. Navigate to the following key in the left-hand pane: {0}
    '''
    '''3. Set the value named {1} in the right-hand pane to {2}.
    '''</summary>
    Friend Shared ReadOnly Property Access_Denied_For_Editing_Registry() As String
        Get
            Return ResourceManager.GetString("Access_Denied_For_Editing_Registry", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Access denied while restarting explorer. If you see this again, disable your anti-virus sofware and try again..
    '''</summary>
    Friend Shared ReadOnly Property Access_Denied_For_Restarting_Explorer() As String
        Get
            Return ResourceManager.GetString("Access_Denied_For_Restarting_Explorer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to take a backup of {0}
    '''
    '''Disable your anti-virus software and restart the app..
    '''</summary>
    Friend Shared ReadOnly Property Access_Denied_For_Taking_Backup() As String
        Get
            Return ResourceManager.GetString("Access_Denied_For_Taking_Backup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} is already open!.
    '''</summary>
    Friend Shared ReadOnly Property Already_Open() As String
        Get
            Return ResourceManager.GetString("Already_Open", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to The user has to be logged off and on to view changes.
    '''
    '''Log off now?.
    '''</summary>
    Friend Shared ReadOnly Property Ask_For_Logoff() As String
        Get
            Return ResourceManager.GetString("Ask_For_Logoff", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Windows has to be restarted to view changes.
    '''
    '''Restart now?.
    '''</summary>
    Friend Shared ReadOnly Property Ask_For_Restart() As String
        Get
            Return ResourceManager.GetString("Ask_For_Restart", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Backup file doesn&apos;t exist for {0}.
    '''</summary>
    Friend Shared ReadOnly Property Backup_File_Does_Not_Exist() As String
        Get
            Return ResourceManager.GetString("Backup_File_Does_Not_Exist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} is of version {1} while its backup is of version {2}.
    '''
    '''The original file was likely replaced to an older backup by a user or an app.
    '''
    '''The backup file&apos;s version is newer, do you want to replace the original file with the backup?.
    '''</summary>
    Friend Shared ReadOnly Property Backup_Version_Newer() As String
        Get
            Return ResourceManager.GetString("Backup_Version_Newer", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} is of version {1} while its backup is of version {2}.
    '''{3}
    '''The backup file&apos;s version is older, do you want to replace it with the original file?.
    '''</summary>
    Friend Shared ReadOnly Property Backup_Version_Older() As String
        Get
            Return ResourceManager.GetString("Backup_Version_Older", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Bitmap file header is already present; Windows won&apos;t display the bitmap.
    '''
    '''Restore the system file from the Advanced option..
    '''</summary>
    Friend Shared ReadOnly Property BitmapFileHeader_Already_Present() As String
        Get
            Return ResourceManager.GetString("BitmapFileHeader_Already_Present", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to delete the existing backup and take a new one for {0}?.
    '''</summary>
    Friend Shared ReadOnly Property Confirm_ReBackup() As String
        Get
            Return ResourceManager.GetString("Confirm_ReBackup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Are you sure you want to delete all existing backups and take new ones?.
    '''</summary>
    Friend Shared ReadOnly Property Confirm_ReBackups() As String
        Get
            Return ResourceManager.GetString("Confirm_ReBackups", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} contains an embedded digital signature by Microsoft. If the file is modified, it will not be loaded by Windows.
    '''
    '''CustomizerGod will load the file as read-only..
    '''</summary>
    Friend Shared ReadOnly Property Embedded_Digital_Signature() As String
        Get
            Return ResourceManager.GetString("Embedded_Digital_Signature", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Enter a feedback message to send!.
    '''</summary>
    Friend Shared ReadOnly Property Enter_Feedback_Message() As String
        Get
            Return ResourceManager.GetString("Enter_Feedback_Message", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Please email hi@kishan.info (or use the Feedback button) and write about the last actions you&apos;ve taken before this error occured so that I can fix it. (Press Ctrl+C to copy the error details)
    '''
    '''{0}.
    '''</summary>
    Friend Shared ReadOnly Property Error_Popup() As String
        Get
            Return ResourceManager.GetString("Error_Popup", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Explorer is not running!.
    '''</summary>
    Friend Shared ReadOnly Property Explorer_Not_Running() As String
        Get
            Return ResourceManager.GetString("Explorer_Not_Running", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to send feedback! Make sure you are connected to the internet..
    '''</summary>
    Friend Shared ReadOnly Property Feedback_Send_Net_Error() As String
        Get
            Return ResourceManager.GetString("Feedback_Send_Net_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Your feedback has been sent! Thanks!.
    '''</summary>
    Friend Shared ReadOnly Property Feedback_Sent() As String
        Get
            Return ResourceManager.GetString("Feedback_Sent", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} doesn&apos;t exist!.
    '''</summary>
    Friend Shared ReadOnly Property File_Does_Not_Exist() As String
        Get
            Return ResourceManager.GetString("File_Does_Not_Exist", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} is not protected by SFC!.
    '''</summary>
    Friend Shared ReadOnly Property File_Not_SFC_Protected() As String
        Get
            Return ResourceManager.GetString("File_Not_SFC_Protected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} restored from {1}.
    '''</summary>
    Friend Shared ReadOnly Property File_Restored() As String
        Get
            Return ResourceManager.GetString("File_Restored", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} is not a valid {1} file!.
    '''</summary>
    Friend Shared ReadOnly Property Invalid_File() As String
        Get
            Return ResourceManager.GetString("Invalid_File", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} failed: {1}.
    '''</summary>
    Friend Shared ReadOnly Property Method_Failed_With_Error() As String
        Get
            Return ResourceManager.GetString("Method_Failed_With_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to No image resources found!.
    '''</summary>
    Friend Shared ReadOnly Property No_Resources() As String
        Get
            Return ResourceManager.GetString("No_Resources", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} {1} returned error:
    '''
    '''{2}.
    '''</summary>
    Friend Shared ReadOnly Property Process_Arguments_Returned_Error() As String
        Get
            Return ResourceManager.GetString("Process_Arguments_Returned_Error", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Select some resources first!.
    '''</summary>
    Friend Shared ReadOnly Property Res_Not_Selected() As String
        Get
            Return ResourceManager.GetString("Res_Not_Selected", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to {0} doesn&apos;t exist. This is a system file and should likely be present in your Windows installation.
    '''
    '''Do you want CustomizerGod to try restoring it?.
    '''</summary>
    Friend Shared ReadOnly Property System_File_Not_Found() As String
        Get
            Return ResourceManager.GetString("System_File_Not_Found", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Unable to remove {0}. Please close other apps, disable your anti-virus software temporarily and try again.
    '''{1}.
    '''</summary>
    Friend Shared ReadOnly Property Unable_To_Remove_File() As String
        Get
            Return ResourceManager.GetString("Unable_To_Remove_File", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Resource {0} has an unknown image format..
    '''</summary>
    Friend Shared ReadOnly Property Unknown_Image_Format() As String
        Get
            Return ResourceManager.GetString("Unknown_Image_Format", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Version {0} is available, you are using version {1}
    '''{2}
    '''Would you like to download it?.
    '''</summary>
    Friend Shared ReadOnly Property Update_Available() As String
        Get
            Return ResourceManager.GetString("Update_Available", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to A new version of CustomizerGod is now available!.
    '''</summary>
    Friend Shared ReadOnly Property Update_Available_Heading() As String
        Get
            Return ResourceManager.GetString("Update_Available_Heading", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to  is available, you are using version {0}.
    '''</summary>
    Friend Shared ReadOnly Property Update_Callout() As String
        Get
            Return ResourceManager.GetString("Update_Callout", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 
    '''What&apos;s new:
    '''{0}
    '''.
    '''</summary>
    Friend Shared ReadOnly Property Update_Changelog() As String
        Get
            Return ResourceManager.GetString("Update_Changelog", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to Windows 8.1 is a free upgrade for Windows 8 users. Upgrade now and enjoy full support.
    '''
    '''To learn more, visit http://j.mp/win8to81.
    '''</summary>
    Friend Shared ReadOnly Property Windows_8_Incompatible() As String
        Get
            Return ResourceManager.GetString("Windows_8_Incompatible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to CustomizerGod currently includes predefined resources for Windows 7, 8.1 and 10 only but you can use it for other files by pressing Ctrl+O..
    '''</summary>
    Friend Shared ReadOnly Property Windows_Incompatible() As String
        Get
            Return ResourceManager.GetString("Windows_Incompatible", resourceCulture)
        End Get
    End Property
    
    '''<summary>
    '''  Looks up a localized string similar to 
    '''The original file was likely updated by Windows Update.
    '''.
    '''</summary>
    Friend Shared ReadOnly Property Windows_Update_Original_File() As String
        Get
            Return ResourceManager.GetString("Windows_Update_Original_File", resourceCulture)
        End Get
    End Property
End Class
